### ISSUE TITLE
Thanks so much for this

### ISSUE THREAD

**Issue by Fatih120** [Ekey/UNIB.Data.Tool#1]
Finding this repo feels like a stroke of luck because I don't know if the person who made unpackers for the prior games is planning to update his. Are you interested in this game at all or was it just a relatively quick side thing for you? I'm interested in modding UNI2 and had a repo set up for documentation but I don't know if other fans of this game are looking into it, even know about this or are interested.

**Comment by Ekey** [comment]
> Finding this repo feels like a stroke of luck because I don't know if the person who made unpackers for the prior games is planning to update his.

You mean my unpacker for MELTY BLOOD: TYPE LUMINA ?

> Are you interested in this game at all or was it just a relatively quick side thing for you?

I just made it for my friend to get sprites, models, textures and etc. :)

**Comment by Fatih120** [comment]
I didn't realize you were the same person who did that one, but I actually meant this one: https://github.com/ucuckic/unist-unpacker
But it seems to be way less efficient in speed compared to yours', and old.

> I just made it for my friend to get sprites, models, textures and etc. :)

Fair enough. Do you know anything about unpacking the OGG music files? They don't appear to be caught by your program, in the `output/Bgm` directory. For example, `d/Jukl0wpzoooPgooo0` is a character theme in OGG format, and I don't believe there's anything else in it. There's a few of these. I don't think the other unpacker I mentioned did this either, but I believe your MBTL unpacker did it just fine for that game.

**Comment by Ekey** [comment]
> air enough. Do you know anything about unpacking the OGG music files? They don't appear to be caught by your program, in the `output/Bgm` directory. For example, `d/Jukl0wpzoooPgooo0` is a character theme in OGG format, and I don't believe there's anything else in it. There's a few of these. I don't think the other unpacker I mentioned did this either, but I believe your MBTL unpacker did it just fine for that game.

In MBTL sounds, music and video files are contained in archives, while in this game they are located outside of them and have no extensions. You can check these files for example (it's a normal Ogg sounds):

```
d/Angf0qfloo6zfobBg
d/Anjf9qfloo6zfobZg
d/bhoononovoon802goobWvbjozMzotmjgfonxow
d/bhoononovoon875goobWvbjozMzotmjgfonxow
d/bhoononovoon884goobWvbjozMzotmjgfonxow
```

You can also check this guide for file descriptions https://steamcommunity.com/sharedfiles/filedetails/?id=1913835223
